version: '3.8'

services:
  db:
    container_name: booking-system-db
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking-system
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-system-network

  redis:
    container_name: booking-system-redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - booking-system-network

volumes:
  postgres_data:

networks:
  booking-system-network:
    driver: bridge
